### ISSUE TITLE
生成后台代码报错，cn.hutool.extra.template.TemplateException: No template found ! Please add one of template jar to your project !

### ISSUE THREAD

**Issue by ding2022** [elunez/eladmin#183]
cn.hutool.extra.template.TemplateException: No template found ! Please add one of template jar to your project !

	at cn.hutool.extra.template.engine.TemplateFactory.doCreate(TemplateFactory.java:75)
	at cn.hutool.extra.template.engine.TemplateFactory.create(TemplateFactory.java:32)
	at cn.hutool.extra.template.TemplateUtil.createEngine(TemplateUtil.java:32)
	at com.xuantu.khronos.util.GenUtil.generatorCode(GenUtil.java:138)
	at com.xuantu.khronos.GeneratorTest.generator(GeneratorTest.java:63)

TemplateFactory 类中需要import com.jfinal.template.Engine;

pom.xml中没有jfinal相关的依赖
需要jfinal吗？是那个版本？

**Comment by ding2022** [comment]
已解决
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>
		</dependency>

**Comment by bruceli19900712** [comment]
你好怎么解决的?  版本问题么

**Comment by ding2022** [comment]
pom文件中增加
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>

**Comment by cheungjingyu** [comment]
打包后，出现这个错误，按照这个方法并没有解决
