### ISSUE TITLE
ERROR m.z.e.handler.GlobalExceptionHandler - cn.hutool.extra.template.TemplateException: No template found ! Please add one of template jar to your project !

### ISSUE THREAD

**Issue by 610152942** [elunez/eladmin#280]
ERROR m.z.e.handler.GlobalExceptionHandler - cn.hutool.extra.template.TemplateException: No template found ! Please add one of template jar to your project !
	at cn.hutool.extra.template.engine.TemplateFactory.doCreate(TemplateFactory.java:43)
	at cn.hutool.extra.template.engine.TemplateFactory.create(TemplateFactory.java:25)
	at cn.hutool.extra.template.TemplateUtil.createEngine(TemplateUtil.java:32)
	at me.zhengjie.utils.GenUtil.generatorCode(GenUtil.java:133)

突然不能使用代码生成器?

**Comment by godslhand** [comment]
<hutool.version>[4.1.12,)</hutool.version>
这里的问题，hutool最新5.2版本有坑，这个写法会自动依赖 最新的，改成5.1.2就行了，我也被坑了好久

**Comment by cool-zhq** [comment]
谢谢大佬   改成  <hutool.version>5.1.2</hutool.version>  就可以了

**Comment by 610152942** [comment]
可以了, 谢谢大佬
