### ISSUE TITLE
2.4版本跑不起来

### ISSUE THREAD

**Issue by devzwy** [elunez/eladmin#344]
```
no libsigar-universal64-macosx.dylib in java.library.path
org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at me.zhengjie.res.ServerMonitorController.<init>(ServerMonitorController.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at me.zhengjie.MonitorRun.main(MonitorRun.java:17)
elAdmin Monitor- 2020-05-05 23:39:39 [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
elAdmin Monitor- 2020-05-05 23:39:39 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8777"]
elAdmin Monitor- 2020-05-05 23:39:39 [main] INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
elAdmin Monitor- 2020-05-05 23:39:39 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8777 (http) with context path ''
elAdmin Monitor- 2020-05-05 23:39:39 [main] INFO  me.zhengjie.MonitorRun - Started MonitorRun in 1.159 seconds (JVM running for 1.535)

```

#### 我死活不知道应该把这些libs加在Java环境的哪个目录下～

**Comment by elunez** [comment]
Sigar 2.5 将会使用 oshi 替代，至于文件放到哪儿，
Window服务器：请将eladmin\eladmin-monitor\src\main\resources目录下的sigar-x86-winnt.dll或者sigar-amd64-winnt.dll 放到java的bin目录下
Linux服务器：请将eladmin\eladmin-monitor\src\main\resources目录下的libsigar-x86-linux.so或者libsigar-amd64-linux.so 放到java的bin目录下

**Comment by devzwy** [comment]
非常感谢您在百忙之中抽出时间回复我的问题，我按照您的方法，将相关.so文件放在对应目录下，依然不行。已经排查到问题并已解决，做一下记录，希望碰到这个问题的同学不要在这个上面浪费时间。  
 
__SignJar 内部调用动态库的代码是__
```
System.load(name);
```
__这里name必须在` java.library.path`这一jvm变量所指向的路径中，要么就会抛出以上错误。
可以使用以下代码查询变量的值,并把相关文件放过去即可__
```
System.getProperty("java.library.path");
```
