### ISSUE TITLE
前台运行报错

### ISSUE THREAD

**Issue by lailailai1203** [elunez/eladmin#423]
你好,我按照文档运行npm run dev 但是编译失败.
 error  in ./src/assets/styles/element-variables.scss

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Package exports for 'D:\project\eladmin\eladmin-web\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:607:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
控制台会报这个错误,请问要怎么解决  (꒦_꒦)

**Comment by elunez** [comment]
检查 npm install 是不是有依赖没安装，推荐使用淘宝的镜像源

```
npm config set registry https://registry.npm.taobao.org
配置后可通过下面方式来验证是否成功
npm config get registry

在 ~/.npmrc 加入下面内容，可以避免安装 node-sass 失败
sass_binary_site=https://npm.taobao.org/mirrors/node-sass/

.npmrc 文件位于
win：C:\Users\[你的账户名称]\.npmrc
linux：直接使用 vi ~/.npmrc
```
