### ISSUE TITLE
密码验证问题

### ISSUE THREAD

**Issue by De-Bufrosa** [elunez/eladmin#50]
成功启动项目后，输入用户名admin密码123456，登录失败，报密码错误异常，info如下，只截取了部分：）   ：

```
elAdmin- 2019-04-29 20:28:48 [http-nio-8000-exec-1] ERROR m.z.e.handler.GlobalExceptionHandler - me.zhengjie.exception.BadRequestException: 密码错误
	at me.zhengjie.aspect.DataScopeAspect.logAround(DataScopeAspect.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
```

经debug，发现在AuthenticationController类的login方法中，发现问题，下面是经`EncryptUtils.encryptPassword(authorizationUser.getPassword());`加密后的用户输入密码：
![201904292036](https://user-images.githubusercontent.com/26758789/56897031-031ce080-6ac0-11e9-91f9-cf1c2fb64475.png)
而数据库中admin对应的密码为：
![201904292038](https://user-images.githubusercontent.com/26758789/56897086-22b40900-6ac0-11e9-8612-0c03dde13d41.png)

erz二者不一致，所以可能`encryptPassword`更新了加密算法，但数据库未及时更新，望解决。

**Comment by elunez** [comment]
1.7 取消了前端MD5加密，因此出现密码不一致的问题， 数据库已经更新了，在system模块的sql文件夹里面
