### ISSUE TITLE
Mac环境本地启动项目，系统监控/服务监控功能获取disk信息存在序列化失败的问题

### ISSUE THREAD

**Issue by Kyle-Larry** [elunez/eladmin#539]
版本: v2.6
环境：本地（Mac环境）
复现步骤：点击 系统监控-服务监控
日志提供：
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.mac.DiskArbitration
	at oshi.software.os.mac.MacFileSystem.getFileStoreMatching(MacFileSystem.java:141)
	at oshi.software.os.mac.MacFileSystem.getFileStores(MacFileSystem.java:124)
	at oshi.software.common.AbstractFileSystem.getFileStores(AbstractFileSystem.java:100)
	at me.zhengjie.modules.system.service.impl.MonitorServiceImpl.getDiskInfo(MonitorServiceImpl.java:75)
	at me.zhengjie.modules.system.service.impl.MonitorServiceImpl.getServers(MonitorServiceImpl.java:60)
	at me.zhengjie.modules.system.rest.MonitorController.query(MonitorController.java:43)
	at me.zhengjie.modules.system.rest.MonitorController$$FastClassBySpringCGLIB$$1c441492.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at me.zhengjie.modules.system.rest.MonitorController$$EnhancerBySpringCGLIB$$93a2c38c.query(<generated>)
	at sun.reflect.GeneratedMethodAccessor340.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:142)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	... 72 more

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/102003098-f35a1a80-3d3d-11eb-8252-241a290ec20e.png)

https://github.com/elunez/eladmin/commit/9591cf3e53c307d42bc82b866f7b096f19120456
