### ISSUE TITLE
redis超时问题

### ISSUE THREAD

**Issue by lzl6261** [elunez/eladmin#556]
版本: v2.6
环境：本地
复现步骤：如果一直使用没问题，但是登陆后长时间不点击，当再次点击的时候会报redis链接超时问题，我的redis服务端是默认安装的
日志提供：
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy272.get(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:66)

**Comment by xuyaojian123** [comment]
我也是这样，本地启动之后，一直操作没有问题，两三分钟没有点击就报redis连接超时问题，不知道怎么解决呢？有没有哪位好心人知道呢？

**Comment by elunez** [comment]
未能复现
