### ISSUE TITLE
如何处理定时任务Task中和数据库相关的业务

### ISSUE THREAD

**Issue by jaliy** [elunez/eladmin#582]
版本: v2.5
环境：本地
复现步骤：新增的定时Task任务，任务中调用Service服务，执行失败
日志提供：
java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.wangjun.modules.quartz.utils.ExecutionJob.executeInternal(ExecutionJob.java:80)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.wangjun.modules.quartz.utils.QuartzRunnable.call(QuartzRunnable.java:55)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.LazyInitializationException: could not initialize proxy [com.wangjun.modules.order.domain.Appointment#38] - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:169)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:309)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
	at com.wangjun.modules.order.domain.Appointment$HibernateProxy$HmB2ajDm.getClinicId(Unknown Source)
	at com.wangjun.notify.task.AppointmentNotifyTask.onAfterNotify(AppointmentNotifyTask.java:118)
	at com.wangjun.notify.task.AppointmentNotifyTask.doExcuse(AppointmentNotifyTask.java:56)
	... 10 more

**Comment by elunez** [comment]
描述模糊，先关闭
