### ISSUE TITLE
centos7定时清理tmp,导致 ip2region.db 会被清理

### ISSUE THREAD

**Issue by abincai** [elunez/eladmin#610]
版本: v2.6
环境：线上
日志提供：
```java
java.io.FileNotFoundException: /tmp/ip2region.db (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at org.lionsoul.ip2region.DbSearcher.<init>(DbSearcher.java:58)
        at me.zhengjie.utils.StringUtils.getLocalCityInfo(StringUtils.java:213)
        at me.zhengjie.utils.StringUtils.getCityInfo(StringUtils.java:193)
        at me.zhengjie.service.impl.LogServiceImpl.save(LogServiceImpl.java:97)
        at me.zhengjie.service.impl.LogServiceImpl$$FastClassBySpringCGLIB$$e201a444.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by abincai** [comment]
改成byte[] 模式，可以不需要创建临时文件。修改方法
