### ISSUE TITLE
启动服务失败

### ISSUE THREAD

**Issue by InVinCiblezz** [elunez/eladmin#628]
今天刚装的最新版(应该是2.6), node 的版本是13.6, 自己本地开发环境，后端已经启动，
在webstorm中安装好依赖后启动dev,
`Failed to compile.

./node_modules/nprogress/nprogress.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/nprogress/nprogress.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for '/Users/xx/workspace/eladmin/eladmin-web/node_modules/colorette'

(@/Users/xx/workspace/eladmin/eladmin-web/postcss.config.js)
    at load (/Users/xx/workspace/eladmin/eladmin-web/node_modules/postcss-load-config/src/plugins.js:28:11)
    at /Users/xx/workspace/eladmin/eladmin-web/node_modules/postcss-load-config/src/plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (/Users/xx/workspace/eladmin/eladmin-web/node_modules/postcss-load-config/src/plugins.js:52:8)
    at processResult (/Users/xx/workspace/eladmin/eladmin-web/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/xx/workspace/eladmin/eladmin-web/node_modules/postcss-load-config/src/index.js:94:14`

请问怎么解决呢？谢谢

**Comment by InVinCiblezz** [comment]
我发现我在命令行直接用npm run dev就没有这个错误，请问这是什么原因，权限吗？
