### ISSUE TITLE
BUGS When Run eladmin-system: APPRUN

### ISSUE THREAD

**Issue by csunking** [elunez/eladmin#780]
Exception Logs：
`
"C:\Program\Dev\JetBrains\IntelliJ IDEA 2021\jbr\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:55217,suspend=y,server=n -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:D:\Pros\IDE\Cache\.IntelliJIdea2019.2\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "E:\Learns\Java\Projs\221112_admin_vue\eladmin\eladmin-system\target\classes;E:\Learns\Java\Projs\221112_admin_vue\eladmin\eladmin-generator\target\classes;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-freemarker\2.6.4\spring-boot-starter-freemarker-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\freemarker\freemarker\2.3.31\freemarker-2.3.31.jar;D:\Pros\IDE\Cache\.m2\repository\commons-configuration\commons-configuration\1.10\commons-configuration-1.10.jar;D:\Pros\IDE\Cache\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\Pros\IDE\Cache\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;E:\Learns\Java\Projs\221112_admin_vue\eladmin\eladmin-tools\target\classes;E:\Learns\Java\Projs\221112_admin_vue\eladmin\eladmin-logging\target\classes;E:\Learns\Java\Projs\221112_admin_vue\eladmin\eladmin-common\target\classes;D:\Pros\IDE\Cache\.m2\repository\cn\hutool\hutool-all\5.7.22\hutool-all-5.7.22.jar;D:\Pros\IDE\Cache\.m2\repository\javax\mail\mail\1.4.7\mail-1.4.7.jar;D:\Pros\IDE\Cache\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\qiniu\qiniu-java-sdk\7.9.3\qiniu-java-sdk-7.9.3.jar;D:\Pros\IDE\Cache\.m2\repository\com\squareup\okhttp3\okhttp\3.14.9\okhttp-3.14.9.jar;D:\Pros\IDE\Cache\.m2\repository\com\squareup\okio\okio\1.17.2\okio-1.17.2.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;D:\Pros\IDE\Cache\.m2\repository\com\alipay\sdk\alipay-sdk-java\4.22.57.ALL\alipay-sdk-java-4.22.57.ALL.jar;D:\Pros\IDE\Cache\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.62\bcprov-jdk15on-1.62.jar;D:\Pros\IDE\Cache\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-websocket\2.6.4\spring-boot-starter-websocket-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-messaging\5.3.16\spring-messaging-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-beans\5.3.16\spring-beans-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-websocket\5.3.16\spring-websocket-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-context\5.3.16\spring-context-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\io\jsonwebtoken\jjwt-api\0.11.2\jjwt-api-0.11.2.jar;D:\Pros\IDE\Cache\.m2\repository\io\jsonwebtoken\jjwt-impl\0.11.2\jjwt-impl-0.11.2.jar;D:\Pros\IDE\Cache\.m2\repository\io\jsonwebtoken\jjwt-jackson\0.11.2\jjwt-jackson-0.11.2.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.13.1\jackson-databind-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.13.1\jackson-annotations-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.13.1\jackson-core-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\org\quartz-scheduler\quartz\2.3.2\quartz-2.3.2.jar;D:\Pros\IDE\Cache\.m2\repository\com\mchange\mchange-commons-java\0.2.15\mchange-commons-java-0.2.15.jar;D:\Pros\IDE\Cache\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\Pros\IDE\Cache\.m2\repository\ch\ethz\ganymed\ganymed-ssh2\build210\ganymed-ssh2-build210.jar;D:\Pros\IDE\Cache\.m2\repository\com\jcraft\jsch\0.1.55\jsch-0.1.55.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\oshi\oshi-core\6.1.4\oshi-core-6.1.4.jar;D:\Pros\IDE\Cache\.m2\repository\net\java\dev\jna\jna\5.10.0\jna-5.10.0.jar;D:\Pros\IDE\Cache\.m2\repository\net\java\dev\jna\jna-platform\5.10.0\jna-platform-5.10.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-data-jpa\2.6.4\spring-boot-starter-data-jpa-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-aop\2.6.4\spring-boot-starter-aop-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\aspectj\aspectjweaver\1.9.7\aspectjweaver-1.9.7.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-jdbc\2.6.4\spring-boot-starter-jdbc-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\com\zaxxer\HikariCP\4.0.3\HikariCP-4.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-jdbc\5.3.16\spring-jdbc-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\jakarta\transaction\jakarta.transaction-api\1.3.3\jakarta.transaction-api-1.3.3.jar;D:\Pros\IDE\Cache\.m2\repository\jakarta\persistence\jakarta.persistence-api\2.2.3\jakarta.persistence-api-2.2.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\hibernate\hibernate-core\5.6.5.Final\hibernate-core-5.6.5.Final.jar;D:\Pros\IDE\Cache\.m2\repository\org\jboss\logging\jboss-logging\3.4.3.Final\jboss-logging-3.4.3.Final.jar;D:\Pros\IDE\Cache\.m2\repository\net\bytebuddy\byte-buddy\1.11.22\byte-buddy-1.11.22.jar;D:\Pros\IDE\Cache\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;D:\Pros\IDE\Cache\.m2\repository\org\jboss\jandex\2.4.2.Final\jandex-2.4.2.Final.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;D:\Pros\IDE\Cache\.m2\repository\org\hibernate\common\hibernate-commons-annotations\5.1.2.Final\hibernate-commons-annotations-5.1.2.Final.jar;D:\Pros\IDE\Cache\.m2\repository\org\glassfish\jaxb\jaxb-runtime\2.3.6\jaxb-runtime-2.3.6.jar;D:\Pros\IDE\Cache\.m2\repository\org\glassfish\jaxb\txw2\2.3.6\txw2-2.3.6.jar;D:\Pros\IDE\Cache\.m2\repository\com\sun\istack\istack-commons-runtime\3.0.12\istack-commons-runtime-3.0.12.jar;D:\Pros\IDE\Cache\.m2\repository\com\sun\activation\jakarta.activation\1.2.2\jakarta.activation-1.2.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\data\spring-data-jpa\2.6.2\spring-data-jpa-2.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\data\spring-data-commons\2.6.2\spring-data-commons-2.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-orm\5.3.16\spring-orm-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-tx\5.3.16\spring-tx-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-aspects\5.3.16\spring-aspects-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-web\2.6.4\spring-boot-starter-web-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter\2.6.4\spring-boot-starter-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot\2.6.4\spring-boot-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-logging\2.6.4\spring-boot-starter-logging-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\ch\qos\logback\logback-classic\1.2.9\logback-classic-1.2.9.jar;D:\Pros\IDE\Cache\.m2\repository\ch\qos\logback\logback-core\1.2.9\logback-core-1.2.9.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.17.0\log4j-to-slf4j-2.17.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;D:\Pros\IDE\Cache\.m2\repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;D:\Pros\IDE\Cache\.m2\repository\org\yaml\snakeyaml\1.29\snakeyaml-1.29.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-json\2.6.4\spring-boot-starter-json-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.13.1\jackson-datatype-jdk8-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.13.1\jackson-datatype-jsr310-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.13.1\jackson-module-parameter-names-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-tomcat\2.6.4\spring-boot-starter-tomcat-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.58\tomcat-embed-core-9.0.58.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.58\tomcat-embed-el-9.0.58.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.58\tomcat-embed-websocket-9.0.58.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-web\5.3.16\spring-web-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-webmvc\5.3.16\spring-webmvc-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-expression\5.3.16\spring-expression-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\jakarta\xml\bind\jakarta.xml.bind-api\2.3.3\jakarta.xml.bind-api-2.3.3.jar;D:\Pros\IDE\Cache\.m2\repository\jakarta\activation\jakarta.activation-api\1.2.2\jakarta.activation-api-1.2.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-core\5.3.16\spring-core-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-jcl\5.3.16\spring-jcl-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-security\2.6.4\spring-boot-starter-security-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-aop\5.3.16\spring-aop-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\security\spring-security-config\5.6.2\spring-security-config-5.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\security\spring-security-core\5.6.2\spring-security-core-5.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\security\spring-security-crypto\5.6.2\spring-security-crypto-5.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\security\spring-security-web\5.6.2\spring-security-web-5.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.4\spring-boot-starter-cache-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-context-support\5.3.16\spring-context-support-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-starter-data-redis\2.6.4\spring-boot-starter-data-redis-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\data\spring-data-redis\2.6.2\spring-data-redis-2.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\data\spring-data-keyvalue\2.6.2\spring-data-keyvalue-2.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\spring-oxm\5.3.16\spring-oxm-5.3.16.jar;D:\Pros\IDE\Cache\.m2\repository\io\lettuce\lettuce-core\6.1.6.RELEASE\lettuce-core-6.1.6.RELEASE.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-common\4.1.74.Final\netty-common-4.1.74.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-handler\4.1.74.Final\netty-handler-4.1.74.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-resolver\4.1.74.Final\netty-resolver-4.1.74.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-buffer\4.1.74.Final\netty-buffer-4.1.74.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-codec\4.1.74.Final\netty-codec-4.1.74.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-tcnative-classes\2.0.48.Final\netty-tcnative-classes-2.0.48.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\netty\netty-transport\4.1.74.Final\netty-transport-4.1.74.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\projectreactor\reactor-core\3.4.15\reactor-core-3.4.15.jar;D:\Pros\IDE\Cache\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\commons\commons-pool2\2.11.1\commons-pool2-2.11.1.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\bgee\log4jdbc-log4j2\log4jdbc-log4j2-jdbc4.1\1.16\log4jdbc-log4j2-jdbc4.1-1.16.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\xiaoymin\knife4j-spring-boot-starter\3.0.3\knife4j-spring-boot-starter-3.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\xiaoymin\knife4j-spring-boot-autoconfigure\3.0.3\knife4j-spring-boot-autoconfigure-3.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\xiaoymin\knife4j-spring\3.0.3\knife4j-spring-3.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\xiaoymin\knife4j-annotations\3.0.3\knife4j-annotations-3.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\io\swagger\swagger-annotations\1.5.22\swagger-annotations-1.5.22.jar;D:\Pros\IDE\Cache\.m2\repository\io\swagger\core\v3\swagger-annotations\2.1.2\swagger-annotations-2.1.2.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\xiaoymin\knife4j-core\3.0.3\knife4j-core-3.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\javassist\javassist\3.25.0-GA\javassist-3.25.0-GA.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-swagger2\3.0.0\springfox-swagger2-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-spi\3.0.0\springfox-spi-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-schema\3.0.0\springfox-schema-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-swagger-common\3.0.0\springfox-swagger-common-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-spring-web\3.0.0\springfox-spring-web-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\github\classgraph\classgraph\4.8.83\classgraph-4.8.83.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-spring-webflux\3.0.0\springfox-spring-webflux-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-spring-webmvc\3.0.0\springfox-spring-webmvc-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-core\3.0.0\springfox-core-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-oas\3.0.0\springfox-oas-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\swagger\core\v3\swagger-models\2.1.2\swagger-models-2.1.2.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-bean-validators\3.0.0\springfox-bean-validators-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\swagger\swagger-models\1.5.22\swagger-models-1.5.22.jar;D:\Pros\IDE\Cache\.m2\repository\io\swagger\swagger-core\1.5.22\swagger-core-1.5.22.jar;D:\Pros\IDE\Cache\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.13.1\jackson-dataformat-yaml-2.13.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\guava\guava\27.0.1-android\guava-27.0.1-android.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\Pros\IDE\Cache\.m2\repository\org\checkerframework\checker-compat-qual\2.5.2\checker-compat-qual-2.5.2.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;D:\Pros\IDE\Cache\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.17\animal-sniffer-annotations-1.17.jar;D:\Pros\IDE\Cache\.m2\repository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-boot-starter\3.0.0\springfox-boot-starter-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\io\springfox\springfox-data-rest\3.0.0\springfox-data-rest-3.0.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\plugin\spring-plugin-core\2.0.0.RELEASE\spring-plugin-core-2.0.0.RELEASE.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\plugin\spring-plugin-metadata\2.0.0.RELEASE\spring-plugin-metadata-2.0.0.RELEASE.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\xiaoymin\knife4j-spring-ui\3.0.3\knife4j-spring-ui-3.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\mysql\mysql-connector-java\8.0.28\mysql-connector-java-8.0.28.jar;D:\Pros\IDE\Cache\.m2\repository\com\alibaba\druid-spring-boot-starter\1.2.8\druid-spring-boot-starter-1.2.8.jar;D:\Pros\IDE\Cache\.m2\repository\com\alibaba\druid\1.2.8\druid-1.2.8.jar;D:\Pros\IDE\Cache\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\2.6.4\spring-boot-autoconfigure-2.6.4.jar;D:\Pros\IDE\Cache\.m2\repository\net\dreamlu\mica-ip2region\2.6.3\mica-ip2region-2.6.3.jar;D:\Pros\IDE\Cache\.m2\repository\net\dreamlu\mica-core\2.6.3\mica-core-2.6.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\projectlombok\lombok\1.18.22\lombok-1.18.22.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\poi\poi\5.2.0\poi-5.2.0.jar;D:\Pros\IDE\Cache\.m2\repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;D:\Pros\IDE\Cache\.m2\repository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;D:\Pros\IDE\Cache\.m2\repository\com\zaxxer\SparseBitSet\1.2\SparseBitSet-1.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\logging\log4j\log4j-api\2.17.0\log4j-api-2.17.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\poi\poi-ooxml\5.2.0\poi-ooxml-5.2.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\poi\poi-ooxml-lite\5.2.0\poi-ooxml-lite-5.2.0.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\xmlbeans\xmlbeans\5.0.3\xmlbeans-5.0.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\virtuald\curvesapi\1.06\curvesapi-1.06.jar;D:\Pros\IDE\Cache\.m2\repository\xerces\xercesImpl\2.12.2\xercesImpl-2.12.2.jar;D:\Pros\IDE\Cache\.m2\repository\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar;D:\Pros\IDE\Cache\.m2\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\Pros\IDE\Cache\.m2\repository\org\mapstruct\mapstruct\1.4.2.Final\mapstruct-1.4.2.Final.jar;D:\Pros\IDE\Cache\.m2\repository\org\mapstruct\mapstruct-processor\1.4.2.Final\mapstruct-processor-1.4.2.Final.jar;D:\Pros\IDE\Cache\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\whvcse\easy-captcha\1.6.2\easy-captcha-1.6.2.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\commons\commons-text\1.10.0\commons-text-1.10.0.jar;D:\Pros\IDE\Cache\.m2\repository\nl\basjes\parse\useragent\yauaa\6.11\yauaa-6.11.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\httpcomponents\client5\httpclient5\5.1.3\httpclient5-5.1.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\httpcomponents\core5\httpcore5\5.1.3\httpcore5-5.1.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\apache\httpcomponents\core5\httpcore5-h2\5.1.3\httpcore5-h2-5.1.3.jar;D:\Pros\IDE\Cache\.m2\repository\com\github\ben-manes\caffeine\caffeine\2.9.3\caffeine-2.9.3.jar;D:\Pros\IDE\Cache\.m2\repository\org\checkerframework\checker-qual\3.19.0\checker-qual-3.19.0.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\errorprone\error_prone_annotations\2.10.0\error_prone_annotations-2.10.0.jar;D:\Pros\IDE\Cache\.m2\repository\nl\basjes\collections\prefixmap\2.0\prefixmap-2.0.jar;D:\Pros\IDE\Cache\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Program\Dev\JetBrains\IntelliJ IDEA 2021\lib\idea_rt.jar" me.zhengjie.AppRun
Connected to the target VM, address: '127.0.0.1:55217', transport: 'socket'
elAdmin- 2022-11-12 13:50:25 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:135)
	at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:514)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:198)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166)
	at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
	at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54)
	at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36)
	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:107)
	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:128)
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:86)
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:311)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297)
	at me.zhengjie.AppRun.main(AppRun.java:51)
Disconnected from the target VM, address: '127.0.0.1:55217', transport: 'socket'

Process finished with exit code 1

`

**Comment by csunking** [comment]
ip设置的问题
