### ISSUE TITLE
后台运行项目成功 但是在登录时报错

### ISSUE THREAD

**Issue by Zzhenping** [elunez/eladmin#829]
elAdmin- 2023-11-03 11:34:16 [el-async-2] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void me.zhengjie.service.impl.SysLogServiceImpl.save(java.lang.String,java.lang.String,java.lang.String,org.aspectj.lang.ProceedingJoinPoint,me.zhengjie.domain.SysLog)
java.lang.NoClassDefFoundError: net/dreamlu/mica/core/utils/StringUtil
	at net.dreamlu.mica.ip2region.core.IpInfo.getAddress(IpInfo.java:69)
	at me.zhengjie.utils.StringUtils.getCityInfo(StringUtils.java:167)
	at me.zhengjie.service.impl.SysLogServiceImpl.save(SysLogServiceImpl.java:95)
	at me.zhengjie.service.impl.SysLogServiceImpl$$FastClassBySpringCGLIB$$9bb1142b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

net.dreamlu.mica.core.utils.StringUtil 包是存在的

**Comment by CoreyXing** [comment]
想问下怎么打开前端界面

**Comment by elunez** [comment]
无法复现
