### ISSUE TITLE
将后台部署到云服务器后，查询在线用户报错。

### ISSUE THREAD

**Issue by jliu243** [elunez/eladmin#854]
将后台部署到云服务器后，查询在线用户报错。
elAdmin- [31m2024-08-05 16:55:42[0;39m [32m[http-nio-8000-exec-7][0;39m [1;
31mERROR[0;39m [1;35mm.z.e.handler.GlobalExceptionHandler[0;39m - java.lang.N
ullPointerException
        at me.zhengjie.modules.security.service.OnlineUserService.lambda$getAll$
0(OnlineUserService.java:102)
        at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
        at java.util.TimSort.sort(Unknown Source)
        at java.util.Arrays.sort(Unknown Source)
        at java.util.ArrayList.sort(Unknown Source)
        at me.zhengjie.modules.security.service.OnlineUserService.getAll(OnlineU
serService.java:102)
        at me.zhengjie.modules.security.service.OnlineUserService.getAll(OnlineU
serService.java:80)
        at me.zhengjie.modules.security.service.OnlineUserService$$FastClassBySp
ringCGLIB$$abc2d19.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:2
18)

**Comment by elunez** [comment]
自己先 debug 看看 at me.zhengjie.modules.security.service.OnlineUserService.getAll(OnlineU
serService.java:102)
at me.zhengjie.modules.security.service.OnlineUserService.getAll(OnlineU
serService.java:80)
at me.zhengjie.modules.security.service.OnlineUserService$$FastClassBySp
ringCGLIB$$abc2d19.invoke()
这几段数据
